bases:
- ../base

resources:
- profiles.yml

patchesJson6902:
  - path: split_voting_west.yml
    target:
      group: split.smi-spec.io
      version: v1alpha1
      kind: TrafficSplit
      name: voting
